"""
Django settings for DemoGuitarProject project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e!e976ywl!nh1(fdkz107^5-r+e5d-f+^la2=fs)y1q2!n6950'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'suit',  # admin theme plugin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web_apps.release_news',  # release news
    'django_summernote',  # RTE plugin
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'DemoGuitarProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DemoGuitarProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-CN'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# --------------------------------------------user setting area---------------------------------------------------------
# 指定static files的位置，否则无法加载静态资源
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


# choose a settings file to use
os.environ['DJANGO_SETTINGS_MODULE'] = 'DemoGuitarProject.settings'

# set the directory for uploading
MEDIA_URL = "upload/"
MEDIA_ROOT = os.path.join(BASE_DIR, "upload")

# TEMPLATE zh_CN
FILE_CHARSET = "utf-8"
DEFAULT_CHARSET = 'utf-8'

# suit settings
SUIT_CONFIG = {

    'ADMIN_NAME': '呆萌后台管理中心',  # 设置后台管理的名称

    'MENU': (

        # Rename app and set icon
        {'app': 'release_news', 'label': '图文管理', 'models':
            (
                'Pages',
                {'label': '发布新闻', 'url': 'release_news.page.add'}  # 通过url来跳转到相应的页面

            )
         },

        {'app': 'django_summernote', 'label': '附件管理'},

    )
}
